services:
  - type: web
    name: churn-predictor
    env: python
    build:
      pythonVersion: 3.10

    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: .
    plan: free
